DROP TABLE IF EXISTS Followings, Reports, Posts, Admins, Users;

CREATE TABLE IF NOT EXISTS `Admins` (
  `id` INTEGER NOT NULL auto_increment , 
  `name` VARCHAR(150), 
  `email` VARCHAR(150) UNIQUE, 
  `password` VARCHAR(5000), 
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  UNIQUE `Admins_email_unique` (`email`), 
  PRIMARY KEY (`id`)) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `Users` (
  `id` INTEGER NOT NULL auto_increment , 
  `name` VARCHAR(150), `email` VARCHAR(150) UNIQUE, 
  `password` VARCHAR(5000), 
  `rhythm` VARCHAR(5000), 
  `phone` VARCHAR(10), 
  `gender` CHAR(10), 
  `age` INTEGER, 
  `status` VARCHAR(2000), 
  `objective` VARCHAR(2000), 
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  UNIQUE `Users_email_unique` (`email`), 
  PRIMARY KEY (`id`)) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `Followings` (
  `id` INTEGER NOT NULL auto_increment , 
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  `UserId` INTEGER, 
  `FollowingId` INTEGER,
  UNIQUE (`UserId`,`FollowingId`),
  PRIMARY KEY (`id`), 
  FOREIGN KEY (`UserId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, 
  FOREIGN KEY (`FollowingId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `Posts` (
  `id` INTEGER NOT NULL auto_increment , 
  `title` VARCHAR(150), 
  `description` VARCHAR(5000), 
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  `UserId` INTEGER, 
  PRIMARY KEY (`id`), 
  FOREIGN KEY (`UserId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `Reports` (
  `id` INTEGER NOT NULL auto_increment , 
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  `UserId` INTEGER, 
  `ReportedId` INTEGER,
  UNIQUE (`UserId`,`ReportedId`),
  PRIMARY KEY (`id`), 
  FOREIGN KEY (`UserId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, 
  FOREIGN KEY (`ReportedId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;

CREATE OR REPLACE TRIGGER MyTrigger BEFORE INSERT ON Users FOR EACH ROW BEGIN IF new.age < 0 THEN SET new.age = -new.age; END IF; END;

CREATE OR REPLACE PROCEDURE CountUsers() BEGIN SELECT COUNT(*) AS count FROM Users; END;
CREATE OR REPLACE PROCEDURE CountAdmins() BEGIN SELECT COUNT(*) AS count FROM Admins; END;

INSERT INTO Admins VALUES (
  DEFAULT,
  'Nithin Reddy',
  'red@gmail.com',
  '$2a$08$GTDWiZhkacEyj0IJRw31h.c4VTj0.H4eli15XSVsrT8WDjeNAgOJy',
  DEFAULT,
  DEFAULT);
